import type { Metadata } from "next";
import LegalLayout, { LegalHeading, LegalSection } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Условия использования",
  description: "Пользовательское соглашение сервиса Мира AI. Правила и условия использования.",
  alternates: { canonical: "https://vmira.ai/legal/terms" },
};

export default function TermsPage() {
  return (
    <LegalLayout>
      <LegalHeading title="Terms of Service" effectiveDate="March 17, 2026" />

      <div className="mb-10 text-[15px] leading-[1.8] text-[#1A1A1A]/70 space-y-4">
        <p>
          Welcome to Mira! Before you access our services, please read these Terms of Service.
        </p>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your use of Mira and other products and services that we may offer for individuals, along with any associated apps, software, and websites (together our &quot;Services&quot;). These Terms are a contract between you and Mira AI (&quot;Mira,&quot; &quot;we,&quot; or &quot;us&quot;). By accessing our Services, you agree to these Terms.
        </p>
        <p>
          Please read our <a href="/legal/privacy" className="underline underline-offset-2 decoration-[#1A1A1A]/20 hover:decoration-[#1A1A1A]/50 transition-colors">Privacy Policy</a>, which describes how we collect and use personal information. These Terms also include our <a href="/legal/usage-policy" className="underline underline-offset-2 decoration-[#1A1A1A]/20 hover:decoration-[#1A1A1A]/50 transition-colors">Usage Policy</a>.
        </p>
      </div>

      <LegalSection title="1. Acceptance of Terms">
        <p>
          By accessing or using Mira (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service.
        </p>
        <p>
          The Service is provided by Mira AI (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). We reserve the right to update these terms at any time. Continued use after changes constitutes acceptance of the modified terms.
        </p>
      </LegalSection>

      <LegalSection title="2. Description of Service">
        <p>
          Mira is an AI-powered conversational assistant. The Service includes text-based chat, file processing, web search capabilities, and related features available through our web interface and API.
        </p>
        <p>
          AI-generated content may contain errors, inaccuracies, or outdated information. You are responsible for verifying any information provided by the Service before relying on it.
        </p>
      </LegalSection>

      <LegalSection title="3. Account Registration">
        <p>
          To access certain features, you must create an account. You agree to provide accurate, current, and complete information during registration and to keep your account information updated.
        </p>
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
        </p>
      </LegalSection>

      <LegalSection title="4. Subscription Plans and Billing">
        <p>
          Mira offers free and paid subscription plans. Paid plans are billed monthly in advance. You may cancel your subscription at any time from your account settings.
        </p>
        <p>
          Refunds are provided on a case-by-case basis. If you cancel a paid plan, you will retain access to paid features until the end of your current billing period.
        </p>
        <p>
          We reserve the right to change pricing with 30 days&apos; notice. Price changes will take effect at the start of your next billing cycle.
        </p>
      </LegalSection>

      <LegalSection title="5. User Content">
        <p>
          You retain ownership of any content you submit to the Service (&quot;User Content&quot;). By using the Service, you grant us a limited license to process your content solely for the purpose of providing the Service.
        </p>
        <p>
          We do not use your conversations to train our models unless you explicitly opt in through your privacy settings.
        </p>
      </LegalSection>

      <LegalSection title="6. Prohibited Uses">
        <p>
          You may not use the Service to generate content that is illegal, harmful, deceptive, or that violates the rights of others. Please refer to our Usage Policy for detailed guidelines on acceptable use.
        </p>
      </LegalSection>

      <LegalSection title="7. Intellectual Property">
        <p>
          The Service, including its design, features, and underlying technology, is owned by Mira AI and protected by intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the Service.
        </p>
        <p>
          Output generated by the AI in response to your prompts may be used by you for any lawful purpose, subject to these terms and applicable law.
        </p>
      </LegalSection>

      <LegalSection title="8. Limitation of Liability">
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that the Service will be uninterrupted, error-free, or that AI outputs will be accurate or suitable for any particular purpose.
        </p>
        <p>
          To the maximum extent permitted by law, Mira AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.
        </p>
      </LegalSection>

      <LegalSection title="9. Termination">
        <p>
          We may suspend or terminate your account if you violate these terms or our Usage Policy. You may delete your account at any time through your account settings.
        </p>
        <p>
          Upon termination, your right to use the Service ceases immediately. We may retain certain data as required by law or for legitimate business purposes.
        </p>
      </LegalSection>

      <LegalSection title="10. Governing Law">
        <p>
          These terms are governed by the laws of the Russian Federation. Any disputes shall be resolved through the courts of competent jurisdiction.
        </p>
      </LegalSection>

      <LegalSection title="11. Contact">
        <p>
          For questions about these terms, contact us at legal@mira.ai.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
